############################################
### Budgetify - PR Build .NET Validation ###
############################################

pool:
  name: Azure Pipelines
  demands: msbuild
  vmImage: windows-latest

trigger: none

pr:
  branches:
    include:
    - master

variables:
- name: buildConfiguration
  value: Release
- name: githubNugetServiceConnection
  value: GithubNugetFeed
- name: projects
  value: '**/*.csproj'

jobs:
- job: job_build_test_backend
  displayName: Budgetify .NET Build & Test
  steps:
  - task: DotNetCoreCLI@2
    displayName: .NET Restore
    inputs:
      command: restore
      feedsToUse: config
      nugetConfigPath: NuGet/nuget.config
      externalFeedCredentials: $(githubNugetServiceConnection)
      noCache: true
      projects: $(projects)
      verbosityRestore: Quiet

  - task: DotNetCoreCLI@2
    displayName: .NET Build
    inputs:
      projects: $(projects)
      arguments: --configuration $(buildConfiguration) --no-restore

  - task: DotNetCoreCLI@2
    displayName: .NET Test
    inputs:
      command: test
      projects: '**/*.Tests.csproj'
      arguments: --configuration $(buildConfiguration) --no-restore --no-build

- job: job_build_database
  displayName: Budgetify Build Database
  steps:
    - task: MSBuild@1
      displayName: Database Build
      inputs:
        solution: Databases/Budgetify.Database/Budgetify.Database.sqlproj
        configuration: $(buildConfiguration)
        clean: true
