############################################
### Budgetify - PR Build .NET Validation ###
############################################

pool:
  name: Azure Pipelines
  demands: msbuild
  vmImage: 'windows-latest'

trigger: none

pr:
  branches:
    include:
    - master

variables:
- name: buildConfiguration
  value: Release
- name: githubServiceConnection
  value: GithubNugetFeed
- name: solution
  value: '**/*.sln'
- group: Github
- name: feedApiKey
  value: $(Test)

jobs:
- job: job_build_test_backend
  displayName: 'Budgetify .NET Build & Test'
  steps:
  - task: CmdLine@2
    displayName: .NET Add Github nuget feed
    inputs:
      script: |
        dotnet nuget add source "https://nuget.pkg.github.com/viktor-stojkoski/index.json" --name "github" --username "viktor.98@hotmail.com" --password "$(feedApiKey)" --store-password-in-clear-text

  - task: CmdLine@2
    displayName: .NET Restore
    inputs:
      script: |
        dotnet nuget list source
        dotnet restore "$(System.DefaultWorkingDirectory)/Budgetify.sln" --no-cache --force --configfile "NuGet/nuget.config"
    continueOnError: true
  
  # - task: CmdLine@2
  #   displayName: .NET Restore
  #   inputs:
  #     script: |
  #       nuget setapikey
  #       dotnet nuget list source
  #   continueOnError: true

  - task: DotNetCoreCLI@2
    displayName: .NET Restore
    inputs:
      command: restore
      feedsToUse: config
      nugetConfigPath: NuGet/nuget.config
      noCache: true
      projects: '**/*.csproj'
    continueOnError: true
  
  - task: DotNetCoreCLI@2
    displayName: .NET Restore
    inputs:
      command: restore
      noCache: true
      projects: '**/*.csproj'
    continueOnError: true

  - task: NuGetCommand@2
    displayName: .NET Restore
    inputs:
      command: restore
      feedsToUse: config
      nugetConfigPath: NuGet/nuget.config
      noCache: true
      restoreSolution: $(solution)
    continueOnError: true
    
  - task: NuGetCommand@2
    displayName: .NET Restore
    inputs:
      command: restore
      feedsToUse: config
      publishFeedCredentials: GithubNugetFeed
      nugetConfigPath: NuGet/nuget.config
      noCache: true
      restoreSolution: $(solution)
    continueOnError: true

  - task: DotNetCoreCLI@2
    displayName: '.NET Build'
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: '.NET Test'
    inputs:
      command: test
      projects: '**/*.Tests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore --no-build'

# - job: job_build_database
#   displayName: 'Budgetify Build Database'
#   steps:
#     - task: MSBuild@1
#       displayName: 'Database Build'
#       inputs:
#         solution: 'Databases/Budgetify.Database/Budgetify.Database.sqlproj'
#         configuration: '$(buildConfiguration)'
#         clean: true
