#########################################
### Budgetify - Deploy Infrastructure ###
#########################################

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

trigger: none
pr: none

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure

    jobs:
      - job: job_deploy_terraform
        displayName: Deploy Terraform
        variables:
          - name: serviceConnection
            value: Azure Subscription
          - name: resourceGroup
            value: rg-budgetify-tfstate
          - name: storageAccount
            value: stbudgetifytfstate
          - name: container
            value: terraform-state
          - name: key
            value: dev.terraform.tfstate

        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform latest

          - task: TerraformTaskV3@3
            displayName: Terraform Init
            inputs:
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(container)
              backendAzureRmKey: $(key)

          - task: TerraformTaskV3@3
            displayName: Terraform Validate
            inputs:
              command: validate

          - task: TerraformTaskV3@3
            displayName: Terraform Plan
            inputs:
              command: plan
              environmentServiceNameAzureRM: $(serviceConnection)

          # - task: TerraformTaskV3@3
          #   displayName: Terraform Apply
          #   inputs:
          #     command: apply
          #     commandOptions: --auto-approve
          #     backendAzureRmResourceGroupName: $(resourceGroup)
          #     backendAzureRmStorageAccountName: $(storageAccount)
          #     backendAzureRmContainerName: $(container)
          #     backendAzureRmKey: $(key)

      - job: job_deploy_scripts
        dependsOn: job_deploy_terraform
        displayName: Deploy Scripts
        steps:
          - task: PowerShell@2
            displayName: Deploy B2C User flows
            inputs:
              filePath: ${{ variables['System.DefaultWorkingDirectory'] }}/Deployments/Infrastructure/Scripts/AzureAdB2C/DeployB2CUserFlows.ps1
              arguments: >
                --ClientId $(clientId)
                --ClientSecret $(clientSecret)
                --TenantId $(tenantId)
                --ApiConnector @{
                  DisplayName = $(apiConnectorDisplayName)
                  TargetUrl = $(apiConnectorTargetUrl)
                  Username = $(apiConnectorUsername)
                  Password = $(apiConnectorPassword)
                }
