#########################################
### Budgetify - Deploy Infrastructure ###
#########################################

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

trigger: none
pr: none

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure

    jobs:
      - job: job_deploy_terraform
        displayName: Deploy Terraform
        variables:
          - name: serviceConnection
            value: Azure Subscription
          - name: resourceGroup
            value: rg-budgetify-tfstate
          - name: storageAccount
            value: stbudgetifytfstate
          - name: container
            value: terraform-state
          - name: key
            value: dev.terraform.tfstate
          - name: workingDirectory
            value: $(System.DefaultWorkingDirectory)/Deployments/Infrastructure/Terraform/Development

        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform latest

          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ variables.serviceConnection }}
              workingDirectory: $(workingDirectory)
              scriptType: pscore
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                $Env:ARM_CLIENT_ID = $env:servicePrincipalId
                $Env:ARM_CLIENT_SECRET = $env:servicePrincipalKey
                $Env:ARM_SUBSCRIPTION_ID = "b55f04c5-29eb-4060-b6fe-58d8503e9c9a"
                $Env:ARM_TENANT_ID = "2589ac95-2ee5-4cdb-9e56-e775181dcfc5"
                Get-ChildItem -Path Env:\
                dir env:
                terraform init `
                  -backend-config='subscription_id="b55f04c5-29eb-4060-b6fe-58d8503e9c9a"' `
                  -backend-config='resource_group_name="rg-budgetify-tfstate"' `
                  -backend-config='storage_account_name="stbudgetifytfstate"' `
                  -backend-config='container_name="terraform-state"' `
                  -backend-config='key="dev.terraform.tfstate"'

          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ variables.serviceConnection }}
              workingDirectory: $(workingDirectory)
              scriptType: pscore
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                $Env:ARM_CLIENT_ID = $env:servicePrincipalId
                $Env:ARM_CLIENT_SECRET = $env:servicePrincipalKey
                $Env:ARM_SUBSCRIPTION_ID = "b55f04c5-29eb-4060-b6fe-58d8503e9c9a"
                $Env:ARM_TENANT_ID = "2589ac95-2ee5-4cdb-9e56-e775181dcfc5"
                $Env:TF_VAR_client_id = $env:servicePrincipalId
                $Env:TF_VAR_client_secret = $env:servicePrincipalKey
                terraform plan

          # - task: TerraformTaskV3@3
          #   displayName: Terraform Init
          #   inputs:
          #     backendServiceArm: ${{ variables.serviceConnection }}
          #     backendAzureRmResourceGroupName: $(resourceGroup)
          #     backendAzureRmStorageAccountName: $(storageAccount)
          #     backendAzureRmContainerName: $(container)
          #     backendAzureRmKey: $(key)
          #     workingDirectory: $(workingDirectory)
          #     runAzLogin: true

          # - task: TerraformTaskV3@3
          #   displayName: Terraform Validate
          #   inputs:
          #     command: validate

          # - task: TerraformTaskV3@3
          #   displayName: Terraform Plan
          #   inputs:
          #     command: plan
          #     environmentServiceNameAzureRM: ${{ variables.serviceConnection }}
          #     backendAzureRmResourceGroupName: $(resourceGroup)
          #     backendAzureRmStorageAccountName: $(storageAccount)
          #     backendAzureRmContainerName: $(container)
          #     backendAzureRmKey: $(key)
          #     workingDirectory: $(workingDirectory)
          #     runAzLogin: true

          # - task: TerraformTaskV3@3
          #   displayName: Terraform Apply
          #   inputs:
          #     command: apply
          #     commandOptions: --auto-approve
          #     backendAzureRmResourceGroupName: $(resourceGroup)
          #     backendAzureRmStorageAccountName: $(storageAccount)
          #     backendAzureRmContainerName: $(container)
          #     backendAzureRmKey: $(key)
          #     workingDirectory: $(workingDirectory)

      - job: job_deploy_scripts
        dependsOn: job_deploy_terraform
        displayName: Deploy Scripts
        steps:
          - task: PowerShell@2
            displayName: Deploy B2C User flows
            inputs:
              filePath: ${{ variables['System.DefaultWorkingDirectory'] }}/Deployments/Infrastructure/Scripts/AzureAdB2C/DeployB2CUserFlows.ps1
              arguments: >
                --ClientId $(clientId)
                --ClientSecret $(clientSecret)
                --TenantId $(tenantId)
                --ApiConnector @{
                  DisplayName = $(apiConnectorDisplayName)
                  TargetUrl = $(apiConnectorTargetUrl)
                  Username = $(apiConnectorUsername)
                  Password = $(apiConnectorPassword)
                }
