version: '3.8'

services:
  # Required services
  mssql.db:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zoki123!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sql.data:/var/opt/mssql

  # Budgetify services
  budgetify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - connectionStrings__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;
      - connectionStrings__sqlConnectionReadonlyString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;ApplicationIntent=READONLY;
      - jobs__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify.Hangfire;User=sa;Password=Zoki123!;
    ports:
      - 55555:80

  budgetify.functions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - connectionStrings__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;
      - connectionStrings__sqlConnectionReadonlyString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;ApplicationIntent=READONLY;
      - azureADB2CApiConnector__username=BudgetifyUser
      - azureADB2CApiConnector__password=(C0zT#5Q*6m6jHxG
    ports:
      - 7071:80

volumes:
  sql.data:
