version: '3.8'

services:
  # Required services
  mssql.db:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Zoki123!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sql.data:/var/opt/mssql

  lt:
    command: lt --port 7071 --local-host budgetify.functions -s budgetify

  # Budgetify services
  budgetify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - connectionStrings__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;
      - connectionStrings__sqlConnectionReadonlyString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;ApplicationIntent=READONLY;
      - jobs__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify.Hangfire;User=sa;Password=Zoki123!;
    ports:
      - 55555:80

  budgetify.functions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7071
      - connectionStrings__sqlConnectionString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;
      - connectionStrings__sqlConnectionReadonlyString=Server=mssql.db,1433;Initial Catalog=Budgetify;MultipleActiveResultSets=True;Application Name=EntityFramework;User=sa;Password=Zoki123!;ApplicationIntent=READONLY;
      - azureADB2CApiConnector__username=BudgetifyUser
      - azureADB2CApiConnector__password=(C0zT#5Q*6m6jHxG
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1
      - FUNCTIONS_WORKER_RUNTIME=dotnet
    ports:
      - 7071:7071
    # Workaround for AuthorizationLevel.Function not working with docker
    # https://github.com/Azure/azure-functions-core-tools/issues/29
    # Mount the azure function core tools to $PATH and start the function using func host start
    # Uncomment next lines to run without Visual Studio
    # user: root
    # command: func host start --no-build --csharp
    # # Change when running from different PC/User or start it with Visual Studio
    # volumes:
    #   - C:\Users\vikto\AppData\Local\AzureFunctionsTools\Releases\4.32.0\cli_x64_Linux:/usr/bin

volumes:
  sql.data:
