CREATE TABLE [dbo].[Test]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Uid] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedOn] SMALLDATETIME NOT NULL, 
    [DeletedOn] SMALLDATETIME NULL, 
    [Name] NVARCHAR(250) NULL, 
    [Address] NVARCHAR(250) NOT NULL
)
